### ISSUE TITLE
Too intrusive

### ISSUE THREAD

**Issue by pigsonthewing** [bjohas/OSM-Wikipedia-Monkey#2]
I find the overlay too intrusive; it appears on more articles that are not geographic, than are.

Could it only appear when a menu link is selected? Or could it automatically filter out articles that are not about geographical entities?

**Comment by bjohas** [comment]
Yeah, I agree. It was intended as a "campaign tool", rather than something that is permanently enabled. Generally, the UI is poor. 

As you suggest: One thing I could do is to make the tool less obtrusive when no OSM data is retrieved for that article, as well as adding an on/off switch/options in the menu.

You don't happen to have experience in developing Wikipedia gadgets? :)

**Comment by pigsonthewing** [comment]
Sadly not!

**Comment by bjohas** [comment]
I've done an update, which puts an on/off switch into the usual Wikipedia menu, under "Tools". At least it allows you to selectively test the Gadget. I might replace the on-off switch with a drop dow menu at some stage that allows you to select different display options, e.g. "off", "on demand", "minimal", "full", etc. For now, I hope this is helpful.

**Comment by bjohas** [comment]
I've done another update. Apart from turning the script on/off in the menu, there are now "show results" and "show map" buttons. The state of these is remembered. Without showing results or map, the script now takes up ~ one line only.

**Comment by pigsonthewing** [comment]
Much better - thank you.

**Comment by bjohas** [comment]
The UI is further improved now, with some standard configurations accessible under 'options', including 'view' and 'view on demand', which hide as much of the UI as possible.
